export const TABLE_SCHEMAS = {
  telemarketing_contacts: {
    label: "Telemarketing",
    addressField: 'indirizzo',
    cityField: 'citta',
    hasCoordinates: true,
    fields: [
      { key: 'nome', label: 'Nome', type: 'text', required: false, maxLength: 100, description: "Nome del contatto" },
      { key: 'cognome', label: 'Cognome', type: 'text', required: false, maxLength: 100, description: "Cognome del contatto" },
      { key: 'nome_azienda', label: 'Azienda', type: 'text', required: false, maxLength: 150, description: "Nome azienda" },
      { key: 'telefono', label: 'Telefono', type: 'text', required: false, maxLength: 50, description: "Recapito telefonico" },
      { key: 'phone_2', label: 'Secondo Telefono', type: 'text', required: false, maxLength: 50, description: "Secondo recapito telefonico" },
      { key: 'email', label: 'Email', type: 'text', required: false, maxLength: 100, description: "Email contatto" },
      { key: 'indirizzo', label: 'Indirizzo', type: 'text', required: false, maxLength: 255, description: "Indirizzo completo" },
      { key: 'citta', label: 'Città', type: 'text', required: false, maxLength: 100, description: "Città" },
      { key: 'regione', label: 'Regione', type: 'text', required: false, maxLength: 100, description: "Regione" },
      { key: 'categoria', label: 'Categoria', type: 'text', required: false, description: "Categoria merceologica" },
      { key: 'note', label: 'Note', type: 'text', required: false, description: "Note aggiuntive" },
      { key: 'data_ultimo_richiamo', label: 'Data Ultimo Richiamo', type: 'date', required: false, description: "Data ultima chiamata" },
      { key: 'stato', label: 'Stato', type: 'text', required: false, maxLength: 50, description: "Stato lead" },
      { key: 'anagrafica_type', label: 'Tipo Anagrafica', type: 'text', required: false, maxLength: 50, description: "Tipo anagrafica" },
      { key: 'agente_id', label: 'Agente (Nome/Email)', type: 'relation', required: false, description: "ID Agente" },
      { key: 'allegati_urls', label: 'Link Allegati', type: 'array', required: false, description: "URLs allegati separati da virgola" }
    ],
    defaultMapping: ['nome', 'cognome', 'telefono', 'email', 'indirizzo', 'citta', 'regione', 'categoria', 'note', 'data_ultimo_richiamo']
  },
  potential_tobacconists: {
    label: "Potenziali Tabaccherie",
    addressField: 'indirizzo',
    cityField: 'citta',
    hasCoordinates: true,
    fields: [
      { key: 'nome', label: 'Nome', type: 'text', required: false, maxLength: 100, description: "Nome titolare" },
      { key: 'cognome', label: 'Cognome', type: 'text', required: false, maxLength: 100, description: "Cognome titolare" },
      { key: 'telefono', label: 'Telefono', type: 'text', required: false, maxLength: 50, description: "Telefono" },
      { key: 'phone_2', label: 'Secondo Telefono', type: 'text', required: false, maxLength: 50, description: "Secondo recapito telefonico" },
      { key: 'email', label: 'Email', type: 'text', required: false, maxLength: 100, description: "Email" },
      { key: 'indirizzo', label: 'Indirizzo', type: 'text', required: false, maxLength: 255, description: "Indirizzo rivendita" },
      { key: 'lat', label: 'Latitudine', type: 'numeric', required: false, description: "Latitudine GPS" },
      { key: 'lng', label: 'Longitudine', type: 'numeric', required: false, description: "Longitudine GPS" },
      { key: 'citta', label: 'Città', type: 'text', required: false, maxLength: 100, description: "Città" },
      { key: 'zona', label: 'Zona', type: 'text', required: false, maxLength: 100, description: "Zona/Quartiere" },
      { key: 'regione', label: 'Regione', type: 'text', required: false, maxLength: 100, description: "Regione" },
      { key: 'agente_id', label: 'Agente (ID)', type: 'relation', required: false, description: "UUID Agente" },
      { key: 'agente_nome', label: 'Agente (Nome - Lookup)', type: 'text', required: false, virtual: true, description: "Nome agente per ricerca" },
      { key: 'categoria', label: 'Categoria', type: 'text', required: false, description: "Categoria" },
      { key: 'caratteristiche', label: 'Caratteristiche', type: 'text', required: false, description: "Dettagli attività" },
      { key: 'stato', label: 'Stato', type: 'text', required: false, maxLength: 50, description: "Stato pratica" },
      { key: 'note', label: 'Note', type: 'text', required: false, description: "Note" },
      { key: 'data_ultimo_richiamo', label: 'Data Ultimo Richiamo', type: 'date', required: false, description: "Data ultimo contatto" },
      { key: 'created_at', label: 'Data Creazione', type: 'date', required: false, description: "Data inserimento" },
      { key: 'numero_rivendita', label: 'Numero Rivendita', type: 'integer', required: false, description: "N. Rivendita Tabacchi" },
      { key: 'numero_ricevitoria', label: 'Numero Ricevitoria', type: 'text', required: false, description: "N. Ricevitoria Lotto" },
      { key: 'tipo_rivendita', label: 'Tipo Rivendita', type: 'text', required: false, description: "Ord/Spec/Pat" },
      { key: 'distributore', label: 'Distributore', type: 'text', required: false, description: "Distributore automatico" },
      { key: 'data_presa_in_carico', label: 'Data Presa in Carico', type: 'date', required: false, description: "Data assegnazione" },
      { key: 'allegati_urls', label: 'Link Allegati', type: 'array', required: false, description: "URLs allegati separati da virgola" }
    ],
    defaultMapping: ['nome', 'cognome', 'telefono', 'indirizzo', 'citta', 'zona', 'note', 'numero_rivendita']
  },
  potential_activities: {
    label: "Potenziali Attività (Acquirenti/Venditori)",
    addressField: 'indirizzo',
    cityField: 'citta',
    hasCoordinates: true,
    fields: [
      { key: 'type', label: 'Tipo (acquirente/venditore)', type: 'text', required: true, maxLength: 50, description: "Tipo di record: 'acquirente' o 'venditore'" },
      { key: 'nome', label: 'Nome', type: 'text', required: false, maxLength: 100, description: "Nome del contatto" },
      { key: 'cognome', label: 'Cognome', type: 'text', required: false, maxLength: 100, description: "Cognome del contatto" },
      { key: 'telefono', label: 'Telefono', type: 'text', required: false, maxLength: 50, description: "Numero di telefono principale" },
      { key: 'phone_2', label: 'Secondo Telefono', type: 'text', required: false, maxLength: 50, description: "Secondo recapito telefonico" },
      { key: 'email', label: 'Email', type: 'text', required: false, maxLength: 100, description: "Indirizzo email" },
      { key: 'indirizzo', label: 'Indirizzo', type: 'text', required: false, maxLength: 255, description: "Indirizzo completo" },
      { key: 'lat', label: 'Latitudine', type: 'numeric', required: false, description: "Coordinata Latitudine" },
      { key: 'lng', label: 'Longitudine', type: 'numeric', required: false, description: "Coordinata Longitudine" },
      { key: 'citta', label: 'Città', type: 'text', required: false, maxLength: 100, description: "Città" },
      { key: 'zona', label: 'Zona', type: 'text', required: false, maxLength: 100, description: "Zona o quartiere" },
      { key: 'regione', label: 'Regione', type: 'text', required: false, maxLength: 100, description: "Regione" },
      { key: 'agente_id', label: 'Agente ID', type: 'relation', required: false, description: "UUID dell'agente assegnato" },
      { key: 'agente_nome', label: 'Agente (Nome)', type: 'text', required: false, virtual: true, description: "Nome dell'agente per ricerca automatica ID" },
      { key: 'note', label: 'Note', type: 'text', required: false, description: "Note libere" },
      { key: 'data_richiamo', label: 'Data Ultimo Richiamo', type: 'date', required: false, description: "Data dell'ultimo contatto/richiamo" },
      { key: 'created_at', label: 'Data Creazione', type: 'date', required: false, description: "Data di creazione del record" },
      { key: 'budget', label: 'Budget', type: 'numeric', required: false, description: "Budget disponibile (Acquirente)" },
      { key: 'locali_min', label: 'Locali Min', type: 'integer', required: false, description: "Numero minimo di locali richiesti" },
      { key: 'locali_max', label: 'Locali Max', type: 'integer', required: false, description: "Numero massimo di locali richiesti" },
      { key: 'mq_min', label: 'MQ Min', type: 'integer', required: false, description: "Metri quadri minimi richiesti" },
      { key: 'mq_max', label: 'MQ Max', type: 'integer', required: false, description: "Metri quadri massimi richiesti" },
      { key: 'bagni_status', label: 'Bagni', type: 'text', required: false, description: "Numero o stato dei bagni (es. '2', 'da ristrutturare')" },
      { key: 'arredo', label: 'Arredo', type: 'text', required: false, description: "Preferenze arredo" },
      { key: 'categoria', label: 'Categoria', type: 'text', required: false, description: "Categoria attività (es. Bar, Tabacchi)" },
      { key: 'caratteristiche', label: 'Caratteristiche', type: 'text', required: false, description: "Caratteristiche specifiche richieste" },
      { key: 'stato_prima_visita', label: 'Stato Prima Visita', type: 'text', required: false, description: "Esito o stato della prima visita" },
      { key: 'stato_prima_visita_data', label: 'Data Prima Visita', type: 'date', required: false, description: "Data della prima visita" },
      { key: 'ricavo', label: 'Ricavi', type: 'numeric', required: false, description: "Ricavi dichiarati (Annuale)" },
      { key: 'locali', label: 'Locali (Esatto)', type: 'integer', required: false, description: "Numero locali esatto (Venditore)" },
      { key: 'mq', label: 'MQ (Esatto)', type: 'integer', required: false, description: "Metri quadri esatti (Venditore)" },
      { key: 'bagni', label: 'Bagni (Esatto)', type: 'integer', required: false, description: "Numero bagni esatto (Venditore)" },
      { key: 'aggi', label: 'Aggi', type: 'text', required: false, description: "Aggi (Tabacchi/Bar)" },
      { key: 'stato', label: 'Stato', type: 'text', required: false, description: "Stato del lead (es. Nuovo, In Trattativa)" },
      { key: 'allegati_urls', label: 'Link Allegati', type: 'array', required: false, description: "URLs allegati separati da virgola" }
    ],
    defaultMapping: ['type', 'nome', 'cognome', 'telefono', 'email', 'citta', 'note']
  },
  properties: {
    label: "Immobili",
    addressField: 'indirizzo',
    cityField: 'citta',
    hasCoordinates: true,
    fields: [
      { key: 'codice', label: 'Codice', type: 'text', required: true, maxLength: 50, description: "Codice univoco immobile" },
      { key: 'numero', label: 'Numero (ID)', type: 'integer', required: false, description: "ID numerico legacy" },
      { key: 'categoria', label: 'Categoria', type: 'text', required: false, maxLength: 100, description: "Categoria immobile" },
      { key: 'tipologia', label: 'Tipologia', type: 'text', required: false, maxLength: 100, description: "Tipologia specifica" },
      { key: 'prezzo', label: 'Prezzo', type: 'numeric', required: false, description: "Prezzo richiesto" },
      { key: 'mq', label: 'MQ', type: 'integer', required: false, description: "Superficie in mq" },
      { key: 'locali', label: 'Locali', type: 'integer', required: false, description: "Numero vani" },
      { key: 'bagni', label: 'Bagni', type: 'integer', required: false, description: "Numero servizi" },
      { key: 'caratteristiche', label: 'Caratteristiche', type: 'array', required: false, description: "Lista caratteristiche" },
      { key: 'citta', label: 'Città', type: 'text', required: false, maxLength: 100, description: "Città" },
      { key: 'indirizzo', label: 'Indirizzo', type: 'text', required: false, maxLength: 255, description: "Indirizzo completo" },
      { key: 'zona', label: 'Zona', type: 'text', required: false, maxLength: 100, description: "Zona" },
      { key: 'regione', label: 'Regione', type: 'text', required: false, maxLength: 100, description: "Regione" },
      { key: 'nome_proprietario', label: 'Nome Proprietario', type: 'text', required: false, maxLength: 100, description: "Nome prop." },
      { key: 'cognome_proprietario', label: 'Cognome Proprietario', type: 'text', required: false, maxLength: 100, description: "Cognome prop." },
      { key: 'telefono_proprietario', label: 'Telefono Proprietario', type: 'text', required: false, maxLength: 50, description: "Tel prop." },
      { key: 'phone_2', label: 'Secondo Telefono', type: 'text', required: false, maxLength: 50, description: "Secondo recapito telefonico" },
      { key: 'email_proprietario', label: 'Email Proprietario', type: 'text', required: false, maxLength: 100, description: "Email prop." },
      { key: 'note', label: 'Note', type: 'text', required: false, description: "Note" },
      { key: 'scadenza_mandato', label: 'Scadenza Mandato', type: 'date', required: false, description: "Data scadenza" },
      { key: 'data_richiamo', label: 'Data Richiamo', type: 'date', required: false, description: "Data prossimo contatto" },
      { key: 'stato', label: 'Stato', type: 'text', required: false, maxLength: 50, description: "Stato immobile" },
      { key: 'agente_id', label: 'Agente (Nome/Email)', type: 'relation', required: false, description: "Agente assegnato" },
      { key: 'allegati_urls', label: 'Link Allegati', type: 'array', required: false, description: "URLs allegati separati da virgola" }
    ],
    defaultMapping: ['codice', 'categoria', 'tipologia', 'prezzo', 'mq', 'citta', 'indirizzo', 'zona', 'regione', 'note', 'stato']
  },
  commercial_activities: {
    label: "Attività Commerciali",
    addressField: 'indirizzo',
    cityField: 'citta',
    hasCoordinates: true,
    fields: [
      { key: 'codice', label: 'Codice', type: 'text', required: false, maxLength: 255, description: "Codice attività" },
      { key: 'numero', label: 'Numero (ID)', type: 'integer', required: false, description: "ID numerico" },
      { key: 'categoria', label: 'Categoria', type: 'text', required: false, description: "Categoria" },
      { key: 'citta', label: 'Città', type: 'text', required: false, maxLength: 100, description: "Città" },
      { key: 'indirizzo', label: 'Indirizzo', type: 'text', required: false, maxLength: 255, description: "Indirizzo" },
      { key: 'zona', label: 'Zona', type: 'text', required: false, maxLength: 255, description: "Zona" },
      { key: 'regione', label: 'Regione', type: 'text', required: false, maxLength: 100, description: "Regione" },
      { key: 'lat', label: 'Latitudine', type: 'numeric', required: false, description: "Lat" },
      { key: 'lng', label: 'Longitudine', type: 'numeric', required: false, description: "Lng" },
      { key: 'aggi', label: 'Aggi', type: 'numeric', required: false, description: "Aggi annuali" },
      { key: 'ricavo', label: 'Ricavo', type: 'numeric', required: false, description: "Ricavi annuali" },
      { key: 'prezzo', label: 'Prezzo', type: 'numeric', required: false, description: "Prezzo vendita" },
      { key: 'mq', label: 'MQ', type: 'integer', required: false, description: "MQ totali" },
      { key: 'nome_proprietario', label: 'Nome Proprietario', type: 'text', required: false, maxLength: 100, description: "Nome prop." },
      { key: 'cognome_proprietario', label: 'Cognome Proprietario', type: 'text', required: false, maxLength: 100, description: "Cognome prop." },
      { key: 'telefono_proprietario', label: 'Telefono Proprietario', type: 'text', required: false, maxLength: 50, description: "Tel prop." },
      { key: 'phone_2', label: 'Secondo Telefono', type: 'text', required: false, maxLength: 50, description: "Secondo recapito telefonico" },
      { key: 'email_proprietario', label: 'Email Proprietario', type: 'text', required: false, maxLength: 100, description: "Email prop." },
      { key: 'note', label: 'Note', type: 'text', required: false, description: "Note" },
      { key: 'scadenza_mandato', label: 'Scadenza Mandato', type: 'date', required: false, description: "Scadenza" },
      { key: 'data_richiamo', label: 'Data Richiamo', type: 'date', required: false, description: "Data richiamo" },
      { key: 'vetrina', label: 'Vetrina', type: 'date', required: false, description: "Data vetrina" },
      { key: 'stato', label: 'Stato', type: 'text', required: false, maxLength: 100, description: "Stato" },
      { key: 'agente_id', label: 'Agente (Nome/Email)', type: 'relation', required: false, description: "Agente" },
      { key: 'allegati_urls', label: 'Link Allegati', type: 'array', required: false, description: "URLs allegati separati da virgola" }
    ],
    defaultMapping: ['categoria', 'citta', 'indirizzo', 'prezzo', 'aggi', 'ricavo', 'mq']
  },
  appointments: {
    label: "Appuntamenti",
    hasCoordinates: false,
    fields: [
      { key: 'title', label: 'Titolo', type: 'text', required: true, maxLength: 150, description: "Titolo appuntamento" },
      { key: 'start_time', label: 'Inizio', type: 'date', required: true, description: "Data ora inizio" },
      { key: 'end_time', label: 'Fine', type: 'date', required: true, description: "Data ora fine" },
      { key: 'agente_id', label: 'Agente (Nome/Email)', type: 'relation', required: false, description: "Agente" }
    ],
    defaultMapping: ['title', 'start_time', 'end_time']
  },
  agents: {
    label: "Agenti",
    hasCoordinates: false,
    fields: [
      { key: 'name', label: 'Nome', type: 'text', required: true, maxLength: 100, description: "Nome completo" },
      { key: 'email', label: 'Email', type: 'text', required: true, maxLength: 100, description: "Email login" },
      { key: 'role', label: 'Ruolo', type: 'text', required: false, maxLength: 50, description: "Ruolo (admin/agent)" },
      { key: 'color', label: 'Colore', type: 'text', required: false, maxLength: 20, description: "Colore calendario" }
    ],
    defaultMapping: ['name', 'email', 'role']
  }
};